# Generated by Django 4.0.3 on 2022-04-18 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 19, 23, 8, 980547)),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(('semester__in', [1, 2])), name='check_valid_semester'),
        ),
    ]
