from .staffenrolmentwin import StaffEnrolmentWindow
from .staffenrolmentupdate import StaffEnrolmentUpdateWindow
from .staffenrolmentupdateidsearch import StaffEnrolmentUpdateIDSearchWindow
from .stafffaceenrolment import StaffFaceEnrolmentWindow
from .stafffaceenrolmentupdate import StaffFaceEnrolmentUpdateWindow
from .stafffingerprintenrolment import StaffFingerprintEnrolmentWindow
from .staffpasswordsetting import StaffPasswordSettingWindow
from .staffpasswordsettingupdate import StaffPasswordSettingUpdateWindow